### ISSUE TITLE
CSV formatting

### ISSUE THREAD

**Issue by petrifiedvoices** [Denubis/EpidocPoC#1] opened 2023-08-04 13:43 UTC
Why is there a different structure between idno and terms, even though they are clearly both multivalued attributes?

title,idno,terms
I.Sicily inscription 2976,"{'filename': 'isic2976', 'tm': '645330', 'phi': '175478', 'uri': 'http://sicily.classics.ox.ac.uk/inscription/isic2976', 'doi': '10.5281/zenodo.4387845'}","[{'key': 'funerary', 'ref': 'http://www.eagle-network.eu/voc/typeins/lod/92.html', 'text': 'funerary (?)'}]"

I have been banging my head how to make it flat and the uneven structure makes it hard, at least for me.

I tried this:

`import pandas as pd

df = pd.read_csv("./output_csv/output.csv") # read the CSV file into a dataframe

df["idno"] = df["idno"].apply(eval) # convert the idno column to a dictionary
df = df.explode("terms") # expand the list of dictionaries into separate rows
df[["idno_filename", "idno_doi"]] = df["idno"][["filename", "doi"]] # extract the filename and doi values from the idno dictionary into separate columns
df[["key", "ref", "text"]] = pd.json_normalize(df["terms"]) # extract the key, ref, and text values from the terms dictionary into separate columns
df = df.drop(["idno", "terms"], axis=1) # drop the idno and terms columns
df = df.fillna("NA") # fill any empty values with NA
print(df) # print the dataframe `

**Comment by Denubis** [comment] 2023-08-05 08:58
Load into json first. The problem is that you are flattening a bad hybrid of csv and json. I will change tonight after beer

**Comment by Denubis** [comment] 2023-08-07 02:56
Resolved with 43d2bc3

**Closed as completed by Denubis** 2023-08-07 02:56 UTC
